# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches:
      - '*'
      - '!master'

jobs:
#  test:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-node@v2
#        with:
#          node-version: 16
#      - run: npm ci
#      - run: npm test
#


  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Fetch all commits
          fetch-depth: 0


  publish-npm-beta:
#    needs: test
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org
      - uses: bcomnes/npm-bump@v2.0.2
        with:
          git_email: blcham@gmail.com
          git_username: blcham
          newversion: minor
          npm_token: ${{secrets.NPM_AUTH_TOKEN}}
      - run: npm ci
      - run: npm run build
      - run: npm publish --tag beta --access public --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}