# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches:
      - '*'
      - '!master'

jobs:
#  test:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-node@v2
#        with:
#          node-version: 16
#      - run: npm ci
#      - run: npm test
#

#  automated-version-bump:
##    needs: test
#    runs-on: ubuntu-latest
#    steps:
#      - uses: phips28/gh-action-bump-version@v9.0.16
#        with:
#          default: prerelease
#          preid: 'prc'

  publish-npm-beta:
#    needs: test
#    needs: automated-version-bump
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org
      - run: npm ci
      - run: npm run build
      - run: npm publish --tag beta --access public --ignore-scripts"
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}