name: Publish NPM Beta Package

on:
  pull_request_target:
    types:
      - closed
    branches:
      - master

jobs:
  publish-npm-beta:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      # Define the master branch as a variable
      TARGET_BRANCH: master

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.merge_commit_sha }}

      - name: Get short SHA
        id: set_sha
        run: echo "SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - uses: "phips28/gh-action-bump-version@master"
        with:
          default: prerelease
          minor-wording: "MINOR RELEASE"
          major-wording: "MAJOR RELEASE"
          patch-wording: "PATCH RELEASE"
          rc-wording: null
          preid: beta-${{ env.SHA_SHORT }}
          skip-tag: "true"
          skip-commit: "true"
          skip-push: "true"
          # Setting `target-branch:` is a workaround to cope with auto-deleted branches upon merge
          target-branch: ${{ github.event.pull_request.merge_commit_sha }}

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org

      - run: npm ci
      - run: npm test
      - run: npm run build
      - run: npm publish --access public --ignore-scripts --tag beta
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
