# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches:
      - '*'
      - '!master'

jobs:
  publish-npm-beta:
#    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: 'phips28/gh-action-bump-version@master'
        with:
          default: prerelease
          rc-wording: null
          preid: ${{ toJSON(github.sha) }}
          skip-tag: 'true'
          skip-commit: 'true'
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org
      - run: npm ci
      - run: npm run build
      - run: npm publish --access public --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}

  add-npm-tag-next:
    runs-on: ubuntu-latest
    needs: publish-npm-beta
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: npm dist-tag add @kbss-cvut/s-forms@${{ toJSON(github.sha) }} next